/*
 * Copyright (c) 2018-2026 DistriNet, KU Leuven (sparta@cs.kuleuven.be)
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 */
/**
 */
package be.kuleuven.cs.distrinet.sparta.spartamodel.provider;

import be.kuleuven.cs.distrinet.sparta.spartamodel.SpartaModelPackage;

import be.kuleuven.cs.distrinet.sparta.spartamodel.util.SpartaModelAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.util.ResourceLocator;

import org.eclipse.emf.edit.domain.EditingDomain;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ChildCreationExtenderManager;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IChildCreationExtender;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class SpartaModelItemProviderAdapterFactory extends SpartaModelAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable, IChildCreationExtender {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This helps manage the child creation extenders.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChildCreationExtenderManager childCreationExtenderManager = new ChildCreationExtenderManager(SpartaModelEditPlugin.INSTANCE, SpartaModelPackage.eNS_URI);

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SpartaModelItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.DataFlow} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataFlowItemProvider dataFlowItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.DataFlow}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataFlowAdapter() {
		if (dataFlowItemProvider == null) {
			dataFlowItemProvider = new DataFlowItemProvider(this);
		}

		return dataFlowItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.ExternalEntity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExternalEntityItemProvider externalEntityItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.ExternalEntity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExternalEntityAdapter() {
		if (externalEntityItemProvider == null) {
			externalEntityItemProvider = new ExternalEntityItemProvider(this);
		}

		return externalEntityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.Process} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProcessItemProvider processItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.Process}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProcessAdapter() {
		if (processItemProvider == null) {
			processItemProvider = new ProcessItemProvider(this);
		}

		return processItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.DataStore} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataStoreItemProvider dataStoreItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.DataStore}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataStoreAdapter() {
		if (dataStoreItemProvider == null) {
			dataStoreItemProvider = new DataStoreItemProvider(this);
		}

		return dataStoreItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.DFDModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DFDModelItemProvider dfdModelItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.DFDModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDFDModelAdapter() {
		if (dfdModelItemProvider == null) {
			dfdModelItemProvider = new DFDModelItemProvider(this);
		}

		return dfdModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.TrustBoundaryContainer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TrustBoundaryContainerItemProvider trustBoundaryContainerItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.TrustBoundaryContainer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTrustBoundaryContainerAdapter() {
		if (trustBoundaryContainerItemProvider == null) {
			trustBoundaryContainerItemProvider = new TrustBoundaryContainerItemProvider(this);
		}

		return trustBoundaryContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.SenderSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SenderSpecificationItemProvider senderSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.SenderSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSenderSpecificationAdapter() {
		if (senderSpecificationItemProvider == null) {
			senderSpecificationItemProvider = new SenderSpecificationItemProvider(this);
		}

		return senderSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.RecipientSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RecipientSpecificationItemProvider recipientSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.RecipientSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRecipientSpecificationAdapter() {
		if (recipientSpecificationItemProvider == null) {
			recipientSpecificationItemProvider = new RecipientSpecificationItemProvider(this);
		}

		return recipientSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.SolutionType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SolutionTypeItemProvider solutionTypeItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.SolutionType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSolutionTypeAdapter() {
		if (solutionTypeItemProvider == null) {
			solutionTypeItemProvider = new SolutionTypeItemProvider(this);
		}

		return solutionTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.Role} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoleItemProvider roleItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.Role}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoleAdapter() {
		if (roleItemProvider == null) {
			roleItemProvider = new RoleItemProvider(this);
		}

		return roleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.CounterMeasure} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CounterMeasureItemProvider counterMeasureItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.CounterMeasure}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCounterMeasureAdapter() {
		if (counterMeasureItemProvider == null) {
			counterMeasureItemProvider = new CounterMeasureItemProvider(this);
		}

		return counterMeasureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.RoleBinding} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoleBindingItemProvider roleBindingItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.RoleBinding}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoleBindingAdapter() {
		if (roleBindingItemProvider == null) {
			roleBindingItemProvider = new RoleBindingItemProvider(this);
		}

		return roleBindingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.Solution} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SolutionItemProvider solutionItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.Solution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSolutionAdapter() {
		if (solutionItemProvider == null) {
			solutionItemProvider = new SolutionItemProvider(this);
		}

		return solutionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.ThreatTypeCatalog} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThreatTypeCatalogItemProvider threatTypeCatalogItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.ThreatTypeCatalog}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThreatTypeCatalogAdapter() {
		if (threatTypeCatalogItemProvider == null) {
			threatTypeCatalogItemProvider = new ThreatTypeCatalogItemProvider(this);
		}

		return threatTypeCatalogItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.SolutionTypeCatalog} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SolutionTypeCatalogItemProvider solutionTypeCatalogItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.SolutionTypeCatalog}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSolutionTypeCatalogAdapter() {
		if (solutionTypeCatalogItemProvider == null) {
			solutionTypeCatalogItemProvider = new SolutionTypeCatalogItemProvider(this);
		}

		return solutionTypeCatalogItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link java.util.Map.Entry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EStringToEBooleanMapItemProvider eStringToEBooleanMapItemProvider;

	/**
	 * This creates an adapter for a {@link java.util.Map.Entry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEStringToEBooleanMapAdapter() {
		if (eStringToEBooleanMapItemProvider == null) {
			eStringToEBooleanMapItemProvider = new EStringToEBooleanMapItemProvider(this);
		}

		return eStringToEBooleanMapItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.ThreatSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThreatSpecificationItemProvider threatSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.ThreatSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThreatSpecificationAdapter() {
		if (threatSpecificationItemProvider == null) {
			threatSpecificationItemProvider = new ThreatSpecificationItemProvider(this);
		}

		return threatSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.ThreatSpecificationCatalog} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThreatSpecificationCatalogItemProvider threatSpecificationCatalogItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.ThreatSpecificationCatalog}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThreatSpecificationCatalogAdapter() {
		if (threatSpecificationCatalogItemProvider == null) {
			threatSpecificationCatalogItemProvider = new ThreatSpecificationCatalogItemProvider(this);
		}

		return threatSpecificationCatalogItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.ThreatType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThreatTypeItemProvider threatTypeItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.ThreatType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThreatTypeAdapter() {
		if (threatTypeItemProvider == null) {
			threatTypeItemProvider = new ThreatTypeItemProvider(this);
		}

		return threatTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.Estimate} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EstimateItemProvider estimateItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.Estimate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEstimateAdapter() {
		if (estimateItemProvider == null) {
			estimateItemProvider = new EstimateItemProvider(this);
		}

		return estimateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link java.util.Map.Entry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThreatTypeToEstimateMapItemProvider threatTypeToEstimateMapItemProvider;

	/**
	 * This creates an adapter for a {@link java.util.Map.Entry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThreatTypeToEstimateMapAdapter() {
		if (threatTypeToEstimateMapItemProvider == null) {
			threatTypeToEstimateMapItemProvider = new ThreatTypeToEstimateMapItemProvider(this);
		}

		return threatTypeToEstimateMapItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link java.util.Map.Entry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EStringToEStringMapItemProvider eStringToEStringMapItemProvider;

	/**
	 * This creates an adapter for a {@link java.util.Map.Entry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEStringToEStringMapAdapter() {
		if (eStringToEStringMapItemProvider == null) {
			eStringToEStringMapItemProvider = new EStringToEStringMapItemProvider(this);
		}

		return eStringToEStringMapItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.OrCompositeThreatType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OrCompositeThreatTypeItemProvider orCompositeThreatTypeItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.OrCompositeThreatType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOrCompositeThreatTypeAdapter() {
		if (orCompositeThreatTypeItemProvider == null) {
			orCompositeThreatTypeItemProvider = new OrCompositeThreatTypeItemProvider(this);
		}

		return orCompositeThreatTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.AndCompositeThreatType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AndCompositeThreatTypeItemProvider andCompositeThreatTypeItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.AndCompositeThreatType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAndCompositeThreatTypeAdapter() {
		if (andCompositeThreatTypeItemProvider == null) {
			andCompositeThreatTypeItemProvider = new AndCompositeThreatTypeItemProvider(this);
		}

		return andCompositeThreatTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.ThreatTypeGroup} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThreatTypeGroupItemProvider threatTypeGroupItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.ThreatTypeGroup}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThreatTypeGroupAdapter() {
		if (threatTypeGroupItemProvider == null) {
			threatTypeGroupItemProvider = new ThreatTypeGroupItemProvider(this);
		}

		return threatTypeGroupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.Condition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConditionItemProvider conditionItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.Condition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConditionAdapter() {
		if (conditionItemProvider == null) {
			conditionItemProvider = new ConditionItemProvider(this);
		}

		return conditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.AndCompositeCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AndCompositeConditionItemProvider andCompositeConditionItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.AndCompositeCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAndCompositeConditionAdapter() {
		if (andCompositeConditionItemProvider == null) {
			andCompositeConditionItemProvider = new AndCompositeConditionItemProvider(this);
		}

		return andCompositeConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.OrCompositeCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OrCompositeConditionItemProvider orCompositeConditionItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.OrCompositeCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOrCompositeConditionAdapter() {
		if (orCompositeConditionItemProvider == null) {
			orCompositeConditionItemProvider = new OrCompositeConditionItemProvider(this);
		}

		return orCompositeConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.NotCompositeCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NotCompositeConditionItemProvider notCompositeConditionItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.NotCompositeCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNotCompositeConditionAdapter() {
		if (notCompositeConditionItemProvider == null) {
			notCompositeConditionItemProvider = new NotCompositeConditionItemProvider(this);
		}

		return notCompositeConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.ConditionList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConditionListItemProvider conditionListItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.ConditionList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConditionListAdapter() {
		if (conditionListItemProvider == null) {
			conditionListItemProvider = new ConditionListItemProvider(this);
		}

		return conditionListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.ImportedThreatCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImportedThreatConditionItemProvider importedThreatConditionItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.ImportedThreatCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImportedThreatConditionAdapter() {
		if (importedThreatConditionItemProvider == null) {
			importedThreatConditionItemProvider = new ImportedThreatConditionItemProvider(this);
		}

		return importedThreatConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.ImportedCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImportedConditionItemProvider importedConditionItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.ImportedCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImportedConditionAdapter() {
		if (importedConditionItemProvider == null) {
			importedConditionItemProvider = new ImportedConditionItemProvider(this);
		}

		return importedConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.AttackerModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttackerModelItemProvider attackerModelItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.AttackerModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttackerModelAdapter() {
		if (attackerModelItemProvider == null) {
			attackerModelItemProvider = new AttackerModelItemProvider(this);
		}

		return attackerModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.AttackerProfile} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttackerProfileItemProvider attackerProfileItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.AttackerProfile}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttackerProfileAdapter() {
		if (attackerProfileItemProvider == null) {
			attackerProfileItemProvider = new AttackerProfileItemProvider(this);
		}

		return attackerProfileItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.DataModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataModelItemProvider dataModelItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.DataModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataModelAdapter() {
		if (dataModelItemProvider == null) {
			dataModelItemProvider = new DataModelItemProvider(this);
		}

		return dataModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.DataType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataTypeItemProvider dataTypeItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.DataType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataTypeAdapter() {
		if (dataTypeItemProvider == null) {
			dataTypeItemProvider = new DataTypeItemProvider(this);
		}

		return dataTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.TransformedData} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TransformedDataItemProvider transformedDataItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.TransformedData}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTransformedDataAdapter() {
		if (transformedDataItemProvider == null) {
			transformedDataItemProvider = new TransformedDataItemProvider(this);
		}

		return transformedDataItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.DataSubjectType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataSubjectTypeItemProvider dataSubjectTypeItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.DataSubjectType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataSubjectTypeAdapter() {
		if (dataSubjectTypeItemProvider == null) {
			dataSubjectTypeItemProvider = new DataSubjectTypeItemProvider(this);
		}

		return dataSubjectTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.PersonalDataType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PersonalDataTypeItemProvider personalDataTypeItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.PersonalDataType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPersonalDataTypeAdapter() {
		if (personalDataTypeItemProvider == null) {
			personalDataTypeItemProvider = new PersonalDataTypeItemProvider(this);
		}

		return personalDataTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.DataSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataSetItemProvider dataSetItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.DataSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataSetAdapter() {
		if (dataSetItemProvider == null) {
			dataSetItemProvider = new DataSetItemProvider(this);
		}

		return dataSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.KVModelElementAnnotation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected KVModelElementAnnotationItemProvider kvModelElementAnnotationItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.KVModelElementAnnotation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createKVModelElementAnnotationAdapter() {
		if (kvModelElementAnnotationItemProvider == null) {
			kvModelElementAnnotationItemProvider = new KVModelElementAnnotationItemProvider(this);
		}

		return kvModelElementAnnotationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.ModelElementAnnotation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModelElementAnnotationItemProvider modelElementAnnotationItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.ModelElementAnnotation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModelElementAnnotationAdapter() {
		if (modelElementAnnotationItemProvider == null) {
			modelElementAnnotationItemProvider = new ModelElementAnnotationItemProvider(this);
		}

		return modelElementAnnotationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link be.kuleuven.cs.distrinet.sparta.spartamodel.ThreatPattern} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThreatPatternItemProvider threatPatternItemProvider;

	/**
	 * This creates an adapter for a {@link be.kuleuven.cs.distrinet.sparta.spartamodel.ThreatPattern}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThreatPatternAdapter() {
		if (threatPatternItemProvider == null) {
			threatPatternItemProvider = new ThreatPatternItemProvider(this);
		}

		return threatPatternItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link java.util.Map.Entry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThreatTypeIDToEstimateMapItemProvider threatTypeIDToEstimateMapItemProvider;

	/**
	 * This creates an adapter for a {@link java.util.Map.Entry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThreatTypeIDToEstimateMapAdapter() {
		if (threatTypeIDToEstimateMapItemProvider == null) {
			threatTypeIDToEstimateMapItemProvider = new ThreatTypeIDToEstimateMapItemProvider(this);
		}

		return threatTypeIDToEstimateMapItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public List<IChildCreationExtender> getChildCreationExtenders() {
		return childCreationExtenderManager.getChildCreationExtenders();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Collection<?> getNewChildDescriptors(Object object, EditingDomain editingDomain) {
		return childCreationExtenderManager.getNewChildDescriptors(object, editingDomain);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ResourceLocator getResourceLocator() {
		return childCreationExtenderManager;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (dataFlowItemProvider != null) dataFlowItemProvider.dispose();
		if (externalEntityItemProvider != null) externalEntityItemProvider.dispose();
		if (processItemProvider != null) processItemProvider.dispose();
		if (dataStoreItemProvider != null) dataStoreItemProvider.dispose();
		if (dfdModelItemProvider != null) dfdModelItemProvider.dispose();
		if (trustBoundaryContainerItemProvider != null) trustBoundaryContainerItemProvider.dispose();
		if (senderSpecificationItemProvider != null) senderSpecificationItemProvider.dispose();
		if (recipientSpecificationItemProvider != null) recipientSpecificationItemProvider.dispose();
		if (solutionTypeItemProvider != null) solutionTypeItemProvider.dispose();
		if (roleItemProvider != null) roleItemProvider.dispose();
		if (counterMeasureItemProvider != null) counterMeasureItemProvider.dispose();
		if (roleBindingItemProvider != null) roleBindingItemProvider.dispose();
		if (solutionItemProvider != null) solutionItemProvider.dispose();
		if (threatTypeCatalogItemProvider != null) threatTypeCatalogItemProvider.dispose();
		if (solutionTypeCatalogItemProvider != null) solutionTypeCatalogItemProvider.dispose();
		if (eStringToEBooleanMapItemProvider != null) eStringToEBooleanMapItemProvider.dispose();
		if (threatSpecificationItemProvider != null) threatSpecificationItemProvider.dispose();
		if (threatSpecificationCatalogItemProvider != null) threatSpecificationCatalogItemProvider.dispose();
		if (threatTypeItemProvider != null) threatTypeItemProvider.dispose();
		if (estimateItemProvider != null) estimateItemProvider.dispose();
		if (threatTypeToEstimateMapItemProvider != null) threatTypeToEstimateMapItemProvider.dispose();
		if (eStringToEStringMapItemProvider != null) eStringToEStringMapItemProvider.dispose();
		if (orCompositeThreatTypeItemProvider != null) orCompositeThreatTypeItemProvider.dispose();
		if (andCompositeThreatTypeItemProvider != null) andCompositeThreatTypeItemProvider.dispose();
		if (threatTypeGroupItemProvider != null) threatTypeGroupItemProvider.dispose();
		if (conditionItemProvider != null) conditionItemProvider.dispose();
		if (andCompositeConditionItemProvider != null) andCompositeConditionItemProvider.dispose();
		if (orCompositeConditionItemProvider != null) orCompositeConditionItemProvider.dispose();
		if (notCompositeConditionItemProvider != null) notCompositeConditionItemProvider.dispose();
		if (conditionListItemProvider != null) conditionListItemProvider.dispose();
		if (importedThreatConditionItemProvider != null) importedThreatConditionItemProvider.dispose();
		if (importedConditionItemProvider != null) importedConditionItemProvider.dispose();
		if (attackerModelItemProvider != null) attackerModelItemProvider.dispose();
		if (attackerProfileItemProvider != null) attackerProfileItemProvider.dispose();
		if (dataModelItemProvider != null) dataModelItemProvider.dispose();
		if (dataTypeItemProvider != null) dataTypeItemProvider.dispose();
		if (transformedDataItemProvider != null) transformedDataItemProvider.dispose();
		if (dataSubjectTypeItemProvider != null) dataSubjectTypeItemProvider.dispose();
		if (personalDataTypeItemProvider != null) personalDataTypeItemProvider.dispose();
		if (dataSetItemProvider != null) dataSetItemProvider.dispose();
		if (kvModelElementAnnotationItemProvider != null) kvModelElementAnnotationItemProvider.dispose();
		if (modelElementAnnotationItemProvider != null) modelElementAnnotationItemProvider.dispose();
		if (threatPatternItemProvider != null) threatPatternItemProvider.dispose();
		if (threatTypeIDToEstimateMapItemProvider != null) threatTypeIDToEstimateMapItemProvider.dispose();
	}

}
