#

pluginName = SPARTA Model Edit Support
providerName = DistriNet

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_DataFlow_type = Data Flow
_UI_DataFlowEntity_type = Data Flow Entity
_UI_ExternalEntity_type = External Entity
_UI_Process_type = Process
_UI_DataStore_type = Data Store
_UI_DFDModel_type = DFD Model
_UI_DFDElement_type = DFD Element
_UI_SecurityElement_type = Security Element
_UI_DFDBoundaryElement_type = DFD Boundary Element
_UI_TrustBoundaryContainer_type = Trust Boundary Container
_UI_InformationDisclosureCountermeasure_type = Information Disclosure Countermeasure
_UI_DirectCounterMeasure_type = Direct Counter Measure
_UI_EncryptedData_type = Encrypted Data
_UI_SenderSpecifiable_type = Sender Specifiable
_UI_RecipientSpecifiable_type = Recipient Specifiable
_UI_SenderSpecification_type = Sender Specification
_UI_RecipientSpecification_type = Recipient Specification
_UI_FlowElement_type = Flow Element
_UI_DFDContainer_type = DFD Container
_UI_SecurityAnnotation_type = Security Annotation
_UI_SolutionType_type = Solution Type
_UI_Role_type = Role
_UI_AbstractThreatType_type = Abstract Threat Type
_UI_CounterMeasure_type = Counter Measure
_UI_RoleBinding_type = Role Binding
_UI_Solution_type = Solution
_UI_Resource_type = Resource
_UI_ThreatTypeCatalog_type = Threat Type Catalog
_UI_SolutionTypeCatalog_type = Solution Type Catalog
_UI_EStringToEBooleanMap_type = EString To EBoolean Map
_UI_ThreatSpecification_type = Threat Specification
_UI_ThreatSpecificationCatalog_type = Threat Specification Catalog
_UI_Asset_type = Asset
_UI_ThreatTypeGroup_type = Threat Type Group
_UI_ThreatType_type = Threat Type
_UI_Estimate_type = Estimate
_UI_ThreatTypeToEstimateMap_type = Threat Type To Estimate Map
_UI_DFDModelElement_type = DFD Model Element
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_DataFlowEntity_send_feature = Send
_UI_DataFlowEntity_receive_feature = Receive
_UI_DFDModel_containedElements_feature = Contained Elements
_UI_DFDModel_resource_feature = Resource
_UI_DFDElement_securityannotation_feature = Securityannotation
_UI_DFDElement_bound_feature = Bound
_UI_SecurityElement_description_feature = Description
_UI_DFDBoundaryElement_crossingFlows_feature = Crossing Flows
_UI_SenderSpecifiable_senderSpecifiedBy_feature = Sender Specified By
_UI_SenderSpecifiable_sender_feature = Sender
_UI_RecipientSpecifiable_recipientSpecifiedBy_feature = Recipient Specified By
_UI_RecipientSpecifiable_recipient_feature = Recipient
_UI_SenderSpecification_specifiesSenderOf_feature = Specifies Sender Of
_UI_RecipientSpecification_specifiesRecipientOf_feature = Specifies Recipient Of
_UI_DFDContainer_containedElements_feature = Contained Elements
_UI_SolutionType_processRoles_feature = Process Roles
_UI_SolutionType_dataFlowRoles_feature = Data Flow Roles
_UI_SolutionType_dataStoreRoles_feature = Data Store Roles
_UI_SolutionType_externalEntityRoles_feature = External Entity Roles
_UI_SolutionType_dataFlowEntity_feature = Data Flow Entity
_UI_SolutionType_countermeasure_feature = Countermeasure
_UI_Role_subjected_feature = Subjected
_UI_AbstractThreatType_enabled_feature = Enabled
_UI_AbstractThreatType_patterns_feature = Patterns
_UI_CounterMeasure_mitigates_feature = Mitigates
_UI_CounterMeasure_securitysubobjective_feature = Securitysubobjective
_UI_CounterMeasure_scope_feature = Scope
_UI_CounterMeasure_subject_feature = Subject
_UI_CounterMeasure_difficulty_feature = Difficulty
_UI_RoleBinding_binds_feature = Binds
_UI_RoleBinding_bindsTo_feature = Binds To
_UI_Solution_securitypattern_feature = Securitypattern
_UI_Solution_rolebinding_feature = Rolebinding
_UI_Resource_securityannotation_feature = Securityannotation
_UI_ThreatTypeCatalog_threat_feature = Threat
_UI_SolutionTypeCatalog_solutionTypes_feature = Solution Types
_UI_EStringToEBooleanMap_key_feature = Key
_UI_EStringToEBooleanMap_value_feature = Value
_UI_ThreatSpecification_threat_feature = Threat
_UI_ThreatSpecification_enabled_feature = Enabled
_UI_ThreatSpecification_types_feature = Types
_UI_ThreatSpecification_patterns_feature = Patterns
_UI_ThreatSpecificationCatalog_threatspecifications_feature = Threatspecifications
_UI_Asset_lossMagnitude_feature = Loss Magnitude
_UI_Asset_estimates_feature = Estimates
_UI_ThreatTypeGroup_subThreatTypes_feature = Sub Threat Types
_UI_Estimate_minimum_feature = Minimum
_UI_Estimate_probable_feature = Probable
_UI_Estimate_maximum_feature = Maximum
_UI_Estimate_confidence_feature = Confidence
_UI_ThreatTypeToEstimateMap_key_feature = Key
_UI_ThreatTypeToEstimateMap_value_feature = Value
_UI_DFDModelElement_name_feature = Name
_UI_Unknown_feature = Unspecified

_UI_Role_bindingType_feature = Binding Type
_UI_SolutionType_roles_feature = Roles
_UI_Role_bindingTypes_feature = Binding Types
_UI_Estimate_name_feature = Name
_UI_CompositeThreatType_type = Composite Threat Type
_UI_OrCompositeThreatType_type = Or Composite Threat Type
_UI_AndCompositeThreatType_type = And Composite Threat Type
_UI_ThreatCategory_type = Threat Category
_UI_AbstractCondition_type = Abstract Condition
_UI_CompositeCondition_type = Composite Condition
_UI_Condition_type = Condition
_UI_AndCompositeCondition_type = And Composite Condition
_UI_OrCompositeCondition_type = Or Composite Condition
_UI_NotCompositeCondition_type = Not Composite Condition
_UI_SingleCompositeCondition_type = Single Composite Condition
_UI_MultipleCompositeCondition_type = Multiple Composite Condition
_UI_ConditionList_type = Condition List
_UI_ImportedCondition_type = Imported Condition
_UI_ThreatTypeCatalog_threatcategory_feature = Threatcategory
_UI_ThreatTypeCatalog_conditionlist_feature = Conditionlist
_UI_CompositeThreatType_subThreatTypes_feature = Sub Threat Types
_UI_ThreatType_condition_feature = Condition
_UI_SingleCompositeCondition_subcondition_feature = Subcondition
_UI_MultipleCompositeCondition_subcondition_feature = Subcondition
_UI_ConditionList_abstractcondition_feature = Abstractcondition
_UI_ImportedCondition_threattype_feature = Threattype
_UI_AImportedCondition_type = AImported Condition
_UI_ImportedThreatCondition_type = Imported Threat Condition
_UI_ImportedThreatCondition_threattype_feature = Threattype
_UI_ImportedCondition_condition_feature = Condition
_UI_AbstractThreatType_title_feature = Title
_UI_AbstractThreatType_additionalInfo_feature = Additional Info
_UI_AbstractThreatType_comments_feature = Comments
_UI_AbstractCondition_title_feature = Title
_UI_AbstractCondition_additionalInfo_feature = Additional Info
_UI_AbstractCondition_comments_feature = Comments
_UI_DFDElementAnnotation_type = DFD Element Annotation
_UI_DFDElement_dfdelementannotation_feature = Dfdelementannotation
_UI_DFDElementAnnotation_dfdelement_feature = Dfdelement
_UI_AttackerModel_type = Attacker Model
_UI_AttackerProfile_type = Attacker Profile
_UI_AttackerModel_attackerProfiles_feature = Attacker Profiles
_UI_AttackerProfile_threatCapability_feature = Threat Capability
_UI_AttackerProfile_probabilityOfAction_feature = Probability Of Action
_UI_AttackerProfile_contactFrequency_feature = Contact Frequency
_UI_AttackerProfile_insider_feature = Insider
_UI_DFDModelElement_description_feature = Description
_UI_AttackerProfile_enabled_feature = Enabled
_UI_IThreatTypeCatalogEntry_type = IThreat Type Catalog Entry
_UI_ICharacteristic_type = ICharacteristic
_UI_ThreatType_characteristic_feature = Characteristic
_UI_AbstractThreatType_characteristic_feature = Characteristic
_UI_SpartaResource_type = Sparta Resource
_UI_SpartaResource_securityannotation_feature = Securityannotation
_UI_DataModel_type = Data Model
_UI_DataType_type = Data Type
_UI_TransformedData_type = Transformed Data
_UI_DFDElement_data_feature = Data
_UI_DataModel_dataElements_feature = Data Elements
_UI_DataType_sensitive_feature = Sensitive
_UI_TransformedData_decKey_feature = Dec Key
_UI_TransformedData_encKey_feature = Enc Key
_UI_TransformedData_datatype_feature = Datatype
_UI_Asset_bound_feature = Bound
_UI_ModelElement_type = Model Element
_UI_DataModelElement_type = Data Model Element
_UI_ModelElement_name_feature = Name
_UI_ModelElement_description_feature = Description
_UI_DataModel_dataModelElements_feature = Data Model Elements
_UI_DataSubjectType_type = Data Subject Type
_UI_PersonalDataType_type = Personal Data Type
_UI_DataSet_type = Data Set
_UI_DataSet_datatypes_feature = Datatypes
_UI_DataSet_datatype_feature = Datatype
_UI_DataSubjectType_personaldatatype_feature = Personaldatatype
_UI_DataSubjectType_sensitivity_feature = Sensitivity
_UI_DataSubjectType_nbrOfSubjects_feature = Nbr Of Subjects
_UI_PersonalDataType_sensitivity_feature = Sensitivity
_UI_PersonalDataType_nbrOfRecords_feature = Nbr Of Records
_UI_PersonalDataType_retention_feature = Retention
_UI_IModelElementAnnotation_type = IModel Element Annotation
_UI_KVModelElementAnnotation_type = KV Model Element Annotation
_UI_ModelElement_annotations_feature = Annotations
_UI_KVModelElementAnnotation_key_feature = Key
_UI_KVModelElementAnnotation_value_feature = Value
_UI_ModelElementAnnotation_type = Model Element Annotation
_UI_ModelElementAnnotation_value_feature = Value
_UI_EStringToEStringMap_type = EString To EString Map
_UI_ThreatPattern_type = Threat Pattern
_UI_EStringToEStringMap_key_feature = Key
_UI_EStringToEStringMap_value_feature = Value
_UI_ThreatPattern_longDescription_feature = Long Description
_UI_ThreatPattern_patterns_feature = Patterns
_UI_ThreatPattern_mapping_feature = Mapping
_UI_ThreatTypeCatalog_imports_feature = Imports
_UI_ThreatTypeCatalog_helperPatterns_feature = Helper Patterns
_UI_ThreatTypeCatalog_package_feature = Package
_UI_ThreatTypeCatalog_patternDependencies_feature = Pattern Dependencies
_UI_ThreatType_threatpattern_feature = Threatpattern
_UI_ThreatTypeCatalog_threattypegroup_feature = Threattypegroup
_UI_AbstractThreatType_superThreatType_feature = Super Threat Type
_UI_ModelElement_id_feature = Id
_UI_CounterMeasure_mitigatedThreatTypeID_feature = Mitigated Threat Type ID
_UI_ThreatTypeIDToEstimateMap_type = Threat Type ID To Estimate Map
_UI_Asset_lossMagnituteByID_feature = Loss Magnitute By ID
_UI_ThreatTypeIDToEstimateMap_value_feature = Value
_UI_ThreatTypeIDToEstimateMap_key_feature = Key
_UI_Asset_lossMagnitudeByID_feature = Loss Magnitude By ID
