<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>be.kuleuven.cs.distrinet.sparta</groupId>
		<artifactId>standalone</artifactId>
		<version>2026.2.0</version>
		<relativePath>..</relativePath>
	</parent>
	<artifactId>sparta-model</artifactId>
	<name>sparta-model</name>
	<description>sparta-model</description>
	<packaging>jar</packaging>

	<dependencies>
		<dependency>
			<groupId>be.kuleuven.cs.distrinet.sparta</groupId>
			<artifactId>be.kuleuven.cs.distrinet.sparta.spartamodel</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.emf</groupId>
			<artifactId>org.eclipse.emf.common</artifactId>
			<scope>compile</scope>
			<exclusions>
				<exclusion>
					<artifactId>org.osgi.foundation</artifactId>
					<groupId>org.apache.felix</groupId>
				</exclusion>
				<exclusion>
					<artifactId>stringtemplate</artifactId>
					<groupId>org.antlr</groupId>
				</exclusion>
				<exclusion>
					<artifactId>cglib</artifactId>
					<groupId>*</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.eclipse.emf</groupId>
			<artifactId>org.eclipse.emf.ecore</artifactId>
			<scope>compile</scope>
			<exclusions>
				<exclusion>
					<artifactId>org.osgi.foundation</artifactId>
					<groupId>org.apache.felix</groupId>
				</exclusion>
				<exclusion>
					<artifactId>stringtemplate</artifactId>
					<groupId>org.antlr</groupId>
				</exclusion>
				<exclusion>
					<artifactId>cglib</artifactId>
					<groupId>*</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.eclipse.emf</groupId>
			<artifactId>org.eclipse.emf.ecore.xmi</artifactId>
			<scope>compile</scope>
			<exclusions>
				<exclusion>
					<artifactId>org.osgi.foundation</artifactId>
					<groupId>org.apache.felix</groupId>
				</exclusion>
				<exclusion>
					<artifactId>stringtemplate</artifactId>
					<groupId>org.antlr</groupId>
				</exclusion>
				<exclusion>
					<artifactId>cglib</artifactId>
					<groupId>*</groupId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>
</project>