source.. = src/
output.. = target/classes
bin.includes = plugin.xml,\
               META-INF/,\
               .,\
               icons/,\
               Application.e4xmi,\
               splash.bmp,\
               plugin_customization.ini,\
               plugin.properties,\
               Splash_side.png,\
               about.ini
