<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>be.kuleuven.cs.distrinet.sparta</groupId>
		<artifactId>standalone</artifactId>
		<version>2026.0.0</version>
		<relativePath>..</relativePath>
	</parent>
	<artifactId>sparta-core</artifactId>
	<name>sparta-core</name>
	<description>sparta-core</description>
	<packaging>jar</packaging>

	<dependencies>
		<dependency>
			<groupId>be.kuleuven.cs.distrinet.sparta</groupId>
			<artifactId>be.kuleuven.cs.distrinet.sparta.core</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>be.kuleuven.cs.distrinet.sparta</groupId>
			<artifactId>be.kuleuven.cs.distrinet.sparta.queries</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>be.kuleuven.cs.distrinet.sparta</groupId>
			<artifactId>sparta-model</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-math3</artifactId>
			<version>3.6.1</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.viatra</groupId>
			<artifactId>viatra-query-runtime</artifactId>
			<version>${viatra.version}</version>
		</dependency>
		<dependency>
				<groupId>org.eclipse.emf</groupId>
				<artifactId>org.eclipse.emf.codegen</artifactId>
				<scope>compile</scope>
			</dependency>
			<dependency>
				<groupId>org.eclipse.emf</groupId>
				<artifactId>org.eclipse.emf.codegen.ecore</artifactId>
				<scope>compile</scope>
			</dependency>
<!-- 		<dependency>
			<groupId>org.eclipse.viatra</groupId>
			<artifactId>org.eclipse.viatra.query.runtime.base</artifactId>
			<version>${viatra.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.viatra</groupId>
			<artifactId>org.eclipse.viatra.query.runtime.localsearch</artifactId>
			<version>${viatra.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.viatra</groupId>
			<artifactId>org.eclipse.viatra.query.runtime.rete</artifactId>
			<version>${viatra.version}</version>
		</dependency> -->
		<dependency>
			<groupId>org.eclipse.viatra</groupId>
			<artifactId>viatra-query-language</artifactId>
			<version>${viatra.version}</version>
		</dependency>
<!-- 		<dependency>
			<groupId>org.eclipse.viatra</groupId>
			<artifactId>org.eclipse.viatra.query.patternlanguage.emf</artifactId>
			<version>${viatra.version}</version>
		</dependency> -->
	</dependencies>

	<build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.3.0</version>
        <executions>
          <execution>
            <id>copy</id>
            <phase>package</phase>
            <goals>
              <goal>copy</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <artifactItems>
            <artifactItem>
              <groupId>be.kuleuven.cs.distrinet.sparta</groupId>
              <artifactId>be.kuleuven.cs.distrinet.sparta.core</artifactId>
              <type>jar</type>
              <overWrite>true</overWrite>
              <outputDirectory>${project.build.directory}</outputDirectory>
<!--               <destFileName>optional-new-name.jar</destFileName> -->
            </artifactItem>
          </artifactItems>
          <outputDirectory>${project.build.directory}/wars</outputDirectory>
          <overWriteReleases>false</overWriteReleases>
          <overWriteSnapshots>true</overWriteSnapshots>
        </configuration>
      </plugin>
    </plugins>
  </build>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.eclipse.xtext</groupId>
				<artifactId>xtext-dev-bom</artifactId>
				<version>2.20.0</version>
				<scope>import</scope>
				<type>pom</type>
			</dependency>
		</dependencies>
	</dependencyManagement>
</project>